Part 1 - Numpy

Use this dataset for the first 4 questions.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]

3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [2]:
import numpy as np
import pandas as pd
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


In [19]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [58]:
# 1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

A=iris_2d[0].reshape(1, -1)
B=iris_2d[1].reshape(1, -1)
print(A)
print(B)
print(A.shape)
print(B.shape)
A_B_v=np.concatenate((A,B),axis=0)
A_B_h=np.concatenate((A,B),axis=1)
print(A_B_h)
print(A_B_v)

[[5.1 3.5 1.4 0.2]]
[[4.9 3.  1.4 0.2]]
(1, 4)
(1, 4)
[[5.1 3.5 1.4 0.2 4.9 3.  1.4 0.2]]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]


In [5]:
# 2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]
intersection=np.intersect1d(A,B)
intersection

array([0.2, 1.4])

In [11]:
# 3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
A_range=A[np.where((A>1) & (A<=5))]
A_range

array([3.5, 1.4])

In [16]:
# 4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
selection=iris_2d[(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)]
selection

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

Part 2 - Pandas

1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [31]:

# 1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df[1::20][['Manufacturer', 'Model','Type']]

Manufacturer     Model     Type
1           NaN    Legend  Midsize
21     Chrysler  Imperial    Large
41        Honda     Civic    Small
61   Mitsubishi    Mirage    Small
81       Subaru    Legacy  Compact

In [42]:
# 2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df[['Min.Price','Max.Price']].isnull().sum())
df['Min.Price']=df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price']=df['Max.Price'].fillna(df['Max.Price'].mean())
df[['Min.Price','Max.Price']]
print(df[['Min.Price','Max.Price']].isnull().sum())

Min.Price    7
Max.Price    5
dtype: int64
Min.Price    0
Max.Price    0
dtype: int64


In [61]:
# 3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

df[df.sum(axis=1)>100]

0   1   2   3
0   35  25  27  36
1   38  36  37  22
3   38  26  36  13
5   34  27  31  27
6   32  19  22  36
7   35  36  39  36
10  21  37  22  38
13  33  35  38  21
14  36  25  21  32